# Honeycomb cluster in hexagon shape, with 24 sites

dim = 2

a0 = [ 1.0, 0.0 ]
a1 = [ 0.5, 0.86602540378443865 ]
b0 = [ 6.2831853071795865, -3.6275987284684357 ]
b1 = [ 0.0, 7.2551974569368714 ]


R0 = [ 2, 2 ]
R1 = [ -2, 4 ]

num_sub = 2
pos_sub0 = [ 0.33333333333333333, 0.33333333333333333 ]
pos_sub1 = [ 0.66666666666666667, 0.66666666666666667 ]


[[sub0]]
site = [  0, -2 ]
[[sub0]]
site = [  1, -2 ]
[[sub0]]
site = [ -1, -1 ]
[[sub0]]
site = [  0, -1 ]
[[sub0]]
site = [  1, -1 ]
[[sub0]]
site = [ -2,  0 ]
[[sub0]]
site = [ -1,  0 ]
[[sub0]]
site = [  0,  0 ]
[[sub0]]
site = [  1,  0 ]
[[sub0]]
site = [ -2,  1 ]
[[sub0]]
site = [ -1,  1 ]
[[sub0]]
site = [  0,  1 ]

[[sub1]]
site = [ -1, -2 ]
[[sub1]]
site = [  0, -2 ]
[[sub1]]
site = [  1, -2 ]
[[sub1]]
site = [ -2, -1 ]
[[sub1]]
site = [ -1, -1 ]
[[sub1]]
site = [  0, -1 ]
[[sub1]]
site = [  1, -1 ]
[[sub1]]
site = [ -2,  0 ]
[[sub1]]
site = [ -1,  0 ]
[[sub1]]
site = [  0,  0 ]
[[sub1]]
site = [ -2,  1 ]
[[sub1]]
site = [ -1,  1 ]
