# Triangular cluster, with N=37 sites (R=3)
# Note: N=3(R^2+R)+1

dim = 2

a0 = [ 1.0, 0.0 ]
a1 = [ 0.5, 0.86602540378443865 ]
b0 = [ 6.2831853071795865, -3.6275987284684357 ]
b1 = [ 0.0, 7.2551974569368714 ]

bc = [ "obc", "obc" ]

tilted = true
R0 = [ 4, 3 ]
R1 = [ -3, 7 ]

num_sub = 1
pos_sub0 = [ 0.0, 0.0 ]

[[sub0]]
site = [  0, -3 ]
[[sub0]]
site = [  1, -3 ]
[[sub0]]
site = [  2, -3 ]
[[sub0]]
site = [  3, -3 ]
[[sub0]]
site = [ -1, -2 ]
[[sub0]]
site = [  0, -2 ]
[[sub0]]
site = [  1, -2 ]
[[sub0]]
site = [  2, -2 ]
[[sub0]]
site = [  3, -2 ]
[[sub0]]
site = [ -2, -1 ]
[[sub0]]
site = [ -1, -1 ]
[[sub0]]
site = [  0, -1 ]
[[sub0]]
site = [  1, -1 ]
[[sub0]]
site = [  2, -1 ]
[[sub0]]
site = [  3, -1 ]
[[sub0]]
site = [ -3,  0 ]
[[sub0]]
site = [ -2,  0 ]
[[sub0]]
site = [ -1,  0 ]
[[sub0]]
site = [  0,  0 ]
[[sub0]]
site = [  1,  0 ]
[[sub0]]
site = [  2,  0 ]
[[sub0]]
site = [  3,  0 ]
[[sub0]]
site = [ -3,  1 ]
[[sub0]]
site = [ -2,  1 ]
[[sub0]]
site = [ -1,  1 ]
[[sub0]]
site = [  0,  1 ]
[[sub0]]
site = [  1,  1 ]
[[sub0]]
site = [  2,  1 ]
[[sub0]]
site = [ -3,  2 ]
[[sub0]]
site = [ -2,  2 ]
[[sub0]]
site = [ -1,  2 ]
[[sub0]]
site = [  0,  2 ]
[[sub0]]
site = [  1,  2 ]
[[sub0]]
site = [ -3,  3 ]
[[sub0]]
site = [ -2,  3 ]
[[sub0]]
site = [ -1,  3 ]
[[sub0]]
site = [  0,  3 ]
